services:
    main:
        image: main-jupyter:latest
        build:
            context: ..
            dockerfile: Dockerfile-jupyter
        ports:
            - 8888:8888
        volumes:
            - /storage:/storage
            - ..:/app
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          capabilities: [gpu]
                          device_ids: ['0']
